### ISSUE TITLE
Wrong Fast Scroll indicators when changing adapter's data

### ISSUE THREAD

**Issue by enricocid** [reddit/IndicatorFastScroll#24]
Hello,

This is happening when changing adapter's data to be the results of search view filtering. Video showing the issue:

https://youtu.be/bXNZBMeEgSE

Not a critical problem, don't know if I'm doing something wrong. 

You can have a look at filtering utility [here](https://github.com/enricocid/Music-Player-GO/blob/ce5847fb33273c5bd94d982d7e43a98235a5c0fa/project/app/src/main/java/com/iven/musicplayergo/ui/Utils.kt#L20)

Setup of IFS [here](https://github.com/enricocid/Music-Player-GO/blob/ce5847fb33273c5bd94d982d7e43a98235a5c0fa/project/app/src/main/java/com/iven/musicplayergo/fragments/ArtistsFragment.kt#L152)

To setup RV I'm using [recyclical](https://github.com/afollestad/recyclical) by @afollestad which uses [DataSource](https://github.com/afollestad/recyclical/blob/master/README.md#datasource) for the construction and manipulation of data.

Probably I will remove IFS while filtering...

Lib version: 1.2.0
Android 9 Sept. patch (Mi A2 lite)

**Comment by DSteve595** [comment]
Will take a look.

**Comment by DSteve595** [comment]
Checked it out.
The problem comes from the fact that when you call `processQuery()`, you're setting a new list of artists on the adapter; however, the fast scroller is still looking at `mArtists`, which contains all the unfiltered artists and isn't being updated.
I'd recommend changing how you handle `setQueryResults` in your adapter, because it can save you from other bugs down the line. There are a lot of ways to fix it. Made a PR with an example of one.
